    [package]
    name = "QiaraSharedV1"
    version = "2.1.1"
    authors = []

    [addresses]
    dev = "0x414d4a03ce2efeb08044ab890862f2ade3d6d24700e2ae1c8dfe0684a23b97b6"
    supra_framework = "0x1"
    std = "0x1"
    aptos_std = "0x1"
    Extensions = "0x1"
    [dev-addresses]

    [dependencies.AptosStdlib]
    git = "https://github.com/Entropy-Foundation/aptos-core.git"
    rev = "dev"
    subdir = "aptos-move/framework/aptos-stdlib"

    [dependencies.SupraFramework]
    git = "https://github.com/Entropy-Foundation/aptos-core.git"
    rev = "dev"
    subdir = "aptos-move/framework/supra-framework"

    [dependencies.QiaraEventV2]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Event'

    [dev-dependencies]