    [package]
    name = "QiaraEventV1"
    version = "1.0.0"
    authors = []

    [addresses]
    event = "0xd92a67fc8e2aff7c3116896868d90ac0538f2e2d0f760c21d03a8225eab5e95e"
    std = "0x1"
    aptos_std = "0x1"
    Extensions = "0x1"
    [dev-addresses]


    [dependencies.AptosStdlib]
    git = "https://github.com/aptos-labs/aptos-core.git"
    rev = "testnet"
    subdir = "aptos-move/framework/aptos-stdlib"

    [dependencies.AptosFramework]
    git = "https://github.com/aptos-labs/aptos-core.git"
    rev = "testnet"
    subdir = "aptos-move/framework/aptos-framework"

    [dev-dependencies]