[package]
name = "QiaraGovernanceV1"
version = "1.0.0"
authors = []

[addresses]
dev = "0x414d4a03ce2efeb08044ab890862f2ade3d6d24700e2ae1c8dfe0684a23b97b6"
supra_framework = "0x1"
[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosStdlib]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-stdlib"

    [dependencies.QiaraMarginV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Margin'

    [dependencies.QiaraEventV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Event'

    [dependencies.QiaraStorageV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Storage'

    [dependencies.QiaraSharedV1]
    git = 'https://github.com/cnhuya/AEXIS-CODE.git'
    rev = 'main'
    subdir = 'Supra/Shared'

[dev-dependencies]